/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/cFiles/main.c to edit this template
 */

/* 
 * File:   Even_Fibonacci_Numbers.c
 * Author: 0076969
 *
 * Created on 1 de abril de 2025, 10:42
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
 and 
, the first 
 terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <stdlib.h>

/*
 * 
 */
int main(int argc, char** argv) {

    long Pnumero = 0;
    long Snumero = 1; 
    long resultado;
    int i;
    long soma = 0;
    
    for(i = 0; i < 100 ; i++){
        
        if(resultado > 4000000)break;
        
        resultado = Pnumero + Snumero;
        Pnumero = Snumero;
        Snumero = resultado;
        
        printf("%ld \n", resultado);
        
        if(resultado % 2 == 0){
            soma+= resultado;
        }
    }
     printf("Soma: %ld \n", soma);
    
    return (EXIT_SUCCESS);
}

